name: ebook_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2
  http: ^0.13.4
  
  firebase_auth: ^3.3.16
  firebase_core: ^1.15.0
  firebase_analytics: ^9.1.6
  cloud_firestore: ^3.1.13
  open_file: ^3.2.1
  path_provider: ^2.0.2

  cupertino_icons: ^1.0.2
  animated_theme_switcher: ^2.0.6
  fluttertoast: ^8.0.9
  visibility_detector: ^0.2.2
  flutter_svg: ^1.0.3
  firebase_storage: ^10.2.15
  firebase_app_check: ^0.0.6+11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/books/
    - assets/images/icons/
    - assets/book_descriptions/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
